%YAML 1.2
---
# Redis
redis:
  host: localhost
  port: 6379
  db: 1
  password: ''

# PostgreSQL
postgresql:
  host: localhost
  port: 5432
  dbname: postgres
  username: postgres
  password: '123456'
